// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"
)

type Project struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Notes       string    `json:"notes"`
	Deadline    int64     `json:"deadline"`
	Complete    bool      `json:"complete"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Task struct {
	ID          int64       `json:"id"`
	UserID      int64       `json:"user_id"`
	ProjectID   int64       `json:"project_id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Notes       string      `json:"notes"`
	Deadline    int64       `json:"deadline"`
	Priority    int64       `json:"priority"`
	Checklist   string      `json:"checklist"`
	Complete    bool        `json:"complete"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	Foreign     interface{} `json:"foreign"`
}

type User struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	LastLogin time.Time `json:"last_login"`
}
