// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"
)

type Project struct {
	ID          int64  `json:"id"`
	UserID      int64  `json:"user_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Notes       string `json:"notes"`
	Deadline    string `json:"deadline"`
	Complete    bool   `json:"complete"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type Task struct {
	ID          int64         `json:"id"`
	UserID      int64         `json:"user_id"`
	ProjectID   sql.NullInt64 `json:"project_id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Notes       string        `json:"notes"`
	Deadline    string        `json:"deadline"`
	Priority    int64         `json:"priority"`
	Complete    bool          `json:"complete"`
	CreatedAt   string        `json:"created_at"`
	UpdatedAt   string        `json:"updated_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	LastLogin time.Time `json:"last_login"`
}
